# Production configuration - only nginx is exposed externally
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"  # For future SSL support
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Uncomment for SSL certificates
      # - ./ssl:/etc/nginx/ssl:ro

  backend:
    environment:
      RUST_LOG: warn

  frontend:
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://yourdomain.com  # Update for production
      INTERNAL_API_URL: http://backend:8000
